### ISSUE TITLE
add tooltips to scatterplot

### ISSUE THREAD

**Issue by blackdotbug** [jacobdv/snuffleupagusses#61]
hover on circles should display at least city name

**Comment by blackdotbug** [comment]
Everything you need to do this is right here: https://oregon.bootcampcontent.com/Oregon_Coding_Bootcamp/uofo-por-data-pt-12-2020-u-c/-/blob/master/01-ClassActivities/16-D3/03-Activities/12-Par_Hair_Metal_Conclusion/Solved/app.js

**Comment by pete6184** [comment]
I'm assuming positioning matter for this. I am planning to put it after line 65 in the scatterplot.js file.

**Comment by blackdotbug** [comment]
take a stab at it @pete6184

**Comment by pete6184** [comment]
I've been trying to work through it but somehow the scatterplot has completely broke this morning and I can't even get it to display now. I'm really confused as to why because it doesn't seem to work no matter what branch I am on. Even when I go back to the old 'pete_branch' from when we did the project the first time and I know nothing was changed it's not displaying.

**Comment by pete6184** [comment]
Aaaaaand the scatter plot is back as mysteriously as it disappeared...

**Comment by blackdotbug** [comment]
I was having to empty cache and hard reload to get javascript changes to take effect, @pete6184.
